# Fairytales with Spice - Docker Compose Configuration
# For local development and testing

version: '3.8'

services:
  # Main application service
  fairytales-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
      - FRONTEND_URL=http://localhost:8080
      # Optional: Add your API keys for testing
      # - XAI_API_KEY=your_grok_api_key_here
      # - ELEVENLABS_API_KEY=your_elevenlabs_api_key_here
    volumes:
      # Mount logs for debugging (optional)
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Development service with hot reload
  fairytales-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: development
    ports:
      - "4200:4200"
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - FRONTEND_URL=http://localhost:4200
    volumes:
      - .:/app
      - /app/node_modules
      - /app/story-generator/node_modules
    profiles:
      - dev
    command: npm run dev

# Optional: Add a reverse proxy for production-like testing
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - fairytales-app
    profiles:
      - prod
    restart: unless-stopped

volumes:
  logs:
    driver: local

networks:
  default:
    name: fairytales-network