// ==================== STANDARDIZED ERROR CODES ====================
// Centralized error code registry to ensure consistency across all services

export const ERROR_CODES = {
  // Input Validation Errors (1xxx)
  INVALID_INPUT: 'INVALID_INPUT',
  INVALID_CREATURE: 'INVALID_CREATURE',
  INVALID_THEMES: 'INVALID_THEMES',
  INVALID_THEME_VALUE: 'INVALID_THEME_VALUE',
  TOO_MANY_THEMES: 'TOO_MANY_THEMES',
  INVALID_SPICY_LEVEL: 'INVALID_SPICY_LEVEL',
  SPICY_LEVEL_OUT_OF_RANGE: 'SPICY_LEVEL_OUT_OF_RANGE',
  INVALID_WORD_COUNT: 'INVALID_WORD_COUNT',
  INVALID_USER_INPUT: 'INVALID_USER_INPUT',
  USER_INPUT_TOO_LONG: 'USER_INPUT_TOO_LONG',
  CONTENT_TOO_LARGE: 'CONTENT_TOO_LARGE',
  MISSING_REQUIRED_FIELD: 'MISSING_REQUIRED_FIELD',
  
  // Authentication & Authorization Errors (2xxx)
  UNAUTHORIZED: 'UNAUTHORIZED',
  MISSING_API_KEY: 'MISSING_API_KEY',
  INVALID_API_KEY: 'INVALID_API_KEY',
  FORBIDDEN: 'FORBIDDEN',
  FORBIDDEN_ORIGIN: 'FORBIDDEN_ORIGIN',
  
  // Rate Limiting Errors (3xxx)
  RATE_LIMITED: 'RATE_LIMITED',
  QUOTA_EXCEEDED: 'QUOTA_EXCEEDED',
  AUDIO_QUOTA_EXCEEDED: 'AUDIO_QUOTA_EXCEEDED',
  IMAGE_QUOTA_EXCEEDED: 'IMAGE_QUOTA_EXCEEDED',
  STORAGE_QUOTA_EXCEEDED: 'STORAGE_QUOTA_EXCEEDED',
  
  // Service Errors (4xxx)
  GENERATION_FAILED: 'GENERATION_FAILED',
  CONTINUATION_FAILED: 'CONTINUATION_FAILED',
  CONVERSION_FAILED: 'CONVERSION_FAILED',
  EXPORT_FAILED: 'EXPORT_FAILED',
  IMAGE_GENERATION_FAILED: 'IMAGE_GENERATION_FAILED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  METHOD_NOT_ALLOWED: 'METHOD_NOT_ALLOWED',
  
  // External API Errors (5xxx)
  AI_SERVICE_ERROR: 'AI_SERVICE_ERROR',
  AI_SERVICE_UNAVAILABLE: 'AI_SERVICE_UNAVAILABLE',
  AUDIO_SERVICE_ERROR: 'AUDIO_SERVICE_ERROR',
  STORAGE_SERVICE_ERROR: 'STORAGE_SERVICE_ERROR',
  UNSUPPORTED_CONTENT: 'UNSUPPORTED_CONTENT',
  UNSUPPORTED_STYLE: 'UNSUPPORTED_STYLE',
  FORMAT_NOT_SUPPORTED: 'FORMAT_NOT_SUPPORTED',
  
  // Resource Errors (6xxx)
  STORY_NOT_FOUND: 'STORY_NOT_FOUND',
  AUDIO_NOT_FOUND: 'AUDIO_NOT_FOUND',
  EXPORT_NOT_FOUND: 'EXPORT_NOT_FOUND',
  MAX_CHAPTERS_REACHED: 'MAX_CHAPTERS_REACHED',
  
  // Content Violation Errors (7xxx)
  CONTENT_VIOLATION: 'CONTENT_VIOLATION',
  
  // Streaming Errors (8xxx)
  STREAMING_CONNECTION_FAILED: 'STREAMING_CONNECTION_FAILED',
  STREAM_INTERRUPTED: 'STREAM_INTERRUPTED'
} as const;

export type ErrorCode = typeof ERROR_CODES[keyof typeof ERROR_CODES];
