// Created: 2025-10-29 08:27 UTC

export type {
  CreatureArchetype,
  NarrativeTone,
  SpicyLevel,
  ChapterBatchSize,
  WordBudget,
  HeatContract,
  HeatTensionMode,
  HeatIntimacyBoundary,
  ThemeSeed,
  StoryBlueprint,
  RelationshipEdge,
  CharacterProfile,
  PlotThread,
  LoreArtifact,
  StoryBeat,
  StoryStateSnapshot,
  StorySummary,
  ChapterDelta,
  GeneratedChapter,
  ChapterBatchEnvelope,
  StoryStateDelta,
  StoryPersistenceReceipt,
  GenerationTelemetry,
  ContinuityExtractionSource,
  ContinuityExtractionReceipt,
  StoryIterationPayload,
  SavedStoryProject,
  StoryLabLibrarySort,
  StoryLabProfilePreferences,
  StoryLabUserProfile,
  CloudLibrarySyncMode,
  CloudLibrarySyncState,
  CloudStoryProjectStorageMode,
  CloudStoryProjectListItem,
  CloudStoryProjectList,
  CloudStoryProjectSaveReceipt,
  CloudStoryProjectLoadResult,
  CloudStoryProjectDeleteReceipt,
  StoryGenerationSeam,
  StoryContinuationSeam,
  StoryPersistenceSeam,
  StreamingProgressChunk,
  StoryLabJob,
  StoryLabJobCreationRequest,
  StoryLabJobCreationResponse,
  StoryLabJobDurability,
  StoryLabJobError,
  StoryLabJobEvent,
  StoryLabJobKind,
  StoryLabJobPaths,
  StoryLabJobStatus,
  EvaluationCriteria,
  EvaluationRequest,
  StoryQualityDimensionId,
  StoryQualityDimensionScore,
  StoryQualityHeuristicReport,
  StoryWorkbenchSession,
  ContinuityPanelViewModel,
  ChapterTimelineEntry,
  ErrorSeverity,
  ErrorLog,
  ErrorLoggingSeam
} from '../../../story-generator/src/app/contracts';

export type ApiResponse<T> = import('../../../story-generator/src/app/contracts').ApiResponse<T>;
export type ApiEnvelope<T> = ApiResponse<T>;
