// Created: 2025-10-29 08:27 UTC

export type {
  CreatureArchetype,
  NarrativeTone,
  SpicyLevel,
  ChapterBatchSize,
  WordBudget,
  HeatContract,
  HeatTensionMode,
  HeatIntimacyBoundary,
  ThemeSeed,
  StoryBlueprint,
  RelationshipEdge,
  CharacterProfile,
  StoryMemoryLifetime,
  PlotThread,
  LoreArtifact,
  StoryBeat,
  StoryStateSnapshot,
  StorySummary,
  ChapterDelta,
  GeneratedChapter,
  ChapterBatchEnvelope,
  StoryStateDelta,
  StoryPersistenceReceipt,
  GenerationTelemetry,
  ContinuityExtractionSource,
  ContinuityExtractionReceipt,
  StoryIterationPayload,
  StoryMemoryCard,
  SavedStoryProject,
  StoryLabLibrarySort,
  StoryLabProfilePreferences,
  StoryLabUserProfile,
  CloudLibrarySyncMode,
  CloudLibrarySyncState,
  StoryLabAuthConfig,
  CloudStoryProjectStorageMode,
  CloudStoryProjectListItem,
  CloudStoryProjectList,
  CloudStoryProjectSaveReceipt,
  CloudStoryProjectLoadResult,
  CloudStoryProjectDeleteReceipt,
  StoryGenerationSeam,
  StoryContinuationSeam,
  StoryPersistenceSeam,
  StreamingProgressChunk,
  StoryLabJob,
  StoryLabJobCreationRequest,
  StoryLabJobCreationResponse,
  StoryLabJobDurability,
  StoryLabJobError,
  StoryLabJobEvent,
  StoryLabDeferredJobKind,
  StoryLabGenerationJobKind,
  StoryLabJobKind,
  StoryLabJobStep,
  StoryLabJobPaths,
  StoryLabJobStatus,
  EvaluationCriteria,
  EvaluationRequest,
  StoryQualityDimensionId,
  StoryQualityDimensionScore,
  StoryQualityHeuristicReport,
  StoryWorkbenchSession,
  ContinuityPanelViewModel,
  ChapterTimelineEntry,
  ErrorSeverity,
  ErrorLog,
  ErrorLoggingSeam
} from '../../../story-generator/src/app/contracts';

export {
  CHAPTER_BATCH_SIZES,
  CREATURE_ARCHETYPES,
  HEAT_INTIMACY_BOUNDARIES,
  HEAT_TENSION_MODES,
  NARRATIVE_TONES,
  SPICY_LEVELS,
  STORY_LAB_DEFERRED_JOB_KINDS,
  STORY_LAB_GENERATION_JOB_KINDS,
  STORY_LAB_JOB_STEPS,
  STORY_LAB_JOB_STEP_LABELS,
  STORY_LAB_LIBRARY_SORTS,
  STORY_LAB_TERMINAL_JOB_STATUSES,
  WORD_BUDGETS,
  formatChapterBatchSizeList,
  isChapterBatchSize,
  isDeferredStoryLabJobKind,
  isStoryLabJobStep,
  isTerminalStoryLabJobStatus
} from '../../../story-generator/src/app/contracts';

// Taken from the API's own contract rather than through the Angular one, which
// now re-exports it from here: the envelope is the backend's, and the Story Lab
// routes answer with exactly the envelope the classic routes do.
export type ApiResponse<T> = import('../types/contracts').ApiResponse<T>;
export type ApiEnvelope<T> = ApiResponse<T>;
